jobs:
  build:
    name: Test Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew bootJar
name: Gradle Package
on:
  repository_dispatch:
    types: trigger-ga___gradle-publish.yml
